### ISSUE TITLE
Possibilities to use dynamic input in config?

### ISSUE THREAD

**Issue by Aquive** [redchamps/butter#3]
Got it working finally. Works exactly as expected. Great work!

I have a question though. To finish my installation I need to symlink the web root to the magento pub folder. Is it possible to use the installation folder e.g. the version as a variable?

from butter-config.php

`'installation_root' => '/data/web/magento2/',`

So when I do:

`butter magento:install 2.4.0`

It will install in:

`/data/web/magento2/240/`

So to make the symlink for the Magento installation to be accassible from the web I would in this case need to do:

`ln -s /data/web/magento2/240/pub ~/public`

So my question is. Is it possible to do something like this? Where version is dynamically inserted?

'post_install_commands' => [
        'ln -s /data/web/magento2/<version>/pub ~/public'
    ],

**Comment by rav-redchamps** [comment]
Hi @Aquive 

In that case seems like you can have only one version installation  accessible via web as each symlink will be with same name.

If you are using nginx as the server then tools supports to create automatic virtual hosts/server blocks

Also, if you're using mac operating system then we will recommend using https://github.com/weprovide/valet-plus there will be no need of any additional symlink command

In linux you may use https://cpriego.github.io/valet-linux/

**Comment by redchamps** [comment]
Closing the issue due to inactivity. Please feel free to reopen, in case further information is available.
